#!/usr/bin/env bash
# This is a script that transfers a file from our client to a server
cat <<EOF > ~/.ssh/config
Host *
StrictHostKeyChecking no
EOF

if [[ $# -lt 3 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp "$1" "$3"@"$2":"$4"
fi

