#!/usr/bin/env bash
# This script configures your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install nginx -y

echo "Hello World!" > /var/www/html/Thepage.html

old_string='server_name _;'
new_string='server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'

sudo sed -i "s/$old_string/$new_string/" /etc/nginx/sites-available/default

sudo service restart
