#!/usr/bin/env bash
# This script adds custom headers to two web servers

custom_header='\t\tadd_header X-Served-By "$(hostname)";'
sudo sed -i "/location \/ {/a${custom_header}" /etc/nginx/sites-available/default
sudo service nginx restart
