#!/usr/bin/env bash
# This script fixes a server that can't connect and listen on port 

if ! sudo iptables -t nat -C PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 80 &> /dev/null; then
	sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 80
fi
