#!/usr/bin/env bash
# This script does different things having to do with process and signals
touch /var/run/myscript.pid
pid=$$
echo "$pid" > /var/run/myscript.pid

	trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM
	trap "echo Y U no love me?!; exit" SIGINT
	trap "rm /var/run/myscript.pid; exit" SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
