#!/usr/bin/env bash
# This script terminates the 4-to_infinity_and_beyond process
pid=$(pidof -s "4-to_infinity_and_beyond")

if [[ -n "$pid" ]]; then
	kill "$pid"
	echo "Terminated"
else
	echo "Not running"
fi
