#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays them the number of occurences of ip http code in decending order.
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
