#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays them the number of occurences of ip http code in decending order.
awk '{count[$1]++} END {for (ip in count) print count[ip], ip, $9}' apache-access.log | sort -k1,1nr
