#!/usr/bin/env bash
# This script configures Nginx

sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default

sudo -u nginx service nginx start
