#!/usr/bin/env bash
# This script configures Nginx

sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default

pkill apache2

sudo chmod 664 /etc/nginx/nginx.conf

sudo -u nginx service nginx restart
